# cluster_config.yml - cluster configuration
__default__:
    account: ACCOUNT
    partition: PARTITION # for example assemblix
    time: 01:00:00 # time limit for each job
    nodes: 1
    ntasks-per-node: 14 #Request n cores be allocated per node.
    chdir: /directory/to/change/to #working dir
    output: a_name_for_my_job-%j.out
    error: a_name_for_my_job-%j.err